[package]
name = "serde-hashkey"
version = "0.1.0"
authors = ["John-John Tedro"]
repository = "https://github.com/udoprog/serde-hashkey"
readme = "README.md"
license = "MIT/Apache-2.0"
description = """
Space efficient, in-memory key based on serde.
"""
keywords = ["serde", "serialization"]
categories = ["encoding"]
edition = "2018"

[badges]
travis-ci = { repository = "udoprog/serde-hashkey" }
maintenance = { status = "actively-developed" }

[dependencies]
serde = { version = "1.0.14", default-features = false }

[dev-dependencies]
serde_derive = { version = "1.0.98", default-features = false }
serde_json = "1.0.40"

[features]
default = ["std"]
std = ["serde/std" ]
